apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectweb
spec:
  selector:
    matchLabels:
      app: projectweb
  template:
    metadata:
      labels:
        app: projectweb
    spec:
      containers:
      - name: projectweb
        image: aniketdadhe/projectweb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
