apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectweb
  labels:
    app: project-sitef
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: projectweb
  template:
    metadata:
      labels:
        app: projectweb
    spec:
      containers:
      - name: projectweb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80